apiVersion: v1
kind: Service
metadata:
  name: prod-deployment-service
  namespace: prod
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: production-deployment
